 '''
['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 ///////////////////////'capitalize',(5)
 ///////////////////////'casefold',(17)
 ///////////////////////'center',(19)
 'count',
 'encode',
 'endswith',
 'expandtabs',
 ///////////////////////'find',(3)
 'format',
 'format_map',
 'index',
 ///////////////////////'isalnum',(8)
 ///////////////////////'isalpha',(15)
 ///////////////////////'isascii',(10)
 ///////////////////////'isdecimal',(6)
 ///////////////////////'isdigit',(18)
 'isidentifier',
 //////////////////////'islower',(2)
 //////////////////////'isnumeric',(4)
 'isprintable',
 'isspace',
 //////////////////////'istitle',(24)
 //////////////////////'isupper',(1)
 //////////////////////'join',(11)
 'ljust',
 //////////////////////'lower',(16)
 //////////////////////'lstrip',(23)
 'maketrans',
 'partition',
 //////////////////////'removeprefix',(9)
 //////////////////////'removesuffix',(19)
 //////////////////////'replace',(7)
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 //////////////////////'rsplit',(14)
 //////////////////////'rstrip',(22)
 //////////////////////'split',(12)
 //////////////////////'splitlines',(13)
 'startswith',
 //////////////////////'strip',(20)
 'swapcase',
 //////////////////////'title',(25)
 'translate',
 'upper',
 'zfill']
'''

